### PR TITLE
more cleanup

### PR DESCRIPTION
**Pull request by celluj34**
- regenerated .gitignore
- added .gitattributes and .editorconfig
- removed unreferenced classes and methods
- use string interpolation

### CODE REVIEW

**Comment by TheLogster** [comment]
FYI: there is some duplication with PR #8, in the XFireClient class.

**Comment by celluj34** [comment]
Sure, that's fine. We just have to handle the merge conflicts when either of these are merged. If you'd like me to fix it on my branch, we can get yours merged first and I can fix the issues on my branch.

**Comment by darcymiranda** [comment]
I haven't had a chance to look at these yet. Give me by the end of the day. I'll merge in @TheLogster first for fairness

**Comment by celluj34** [comment]
@darcymiranda Sorry for all the noise. After rebasing against master after all the PRs this is now ready for you to review.

**Review by darcymiranda — APPROVED** [review]
Ahh I forgot to update the namespace again /facepalm. Thanks for checking that and cleaning up all the other warnings

**Pull request merged**
