### PR TITLE
convert Topshelf service to Microsoft.Extensions.Hosting.* service

### PR DESCRIPTION
**Pull request by celluj34**
Windows Services are now 1st party offerings in .Net land, so we don't need to use Topshelf anymore. I updated the install/uninstall scripts to accommodate this, since Topshelf used to do it. We can use [sc create](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create) and [sc delete](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-delete) in its place, which is likely what Topshelf was doing under the covers anyway.

This means that we don't need separate `PFire.Console` and `PFire.WindowsService` projects, since we can debug `IHostedService`s in Visual Studio, so I have removed the `PFire.Console` project.

### CODE REVIEW

**Comment by darcymiranda** [comment]
The reason for PFire.Console is to support linux or rather non-windows installs. Is the .net native support for services cross platform?

**Comment by celluj34** [comment]
I don't actually know. I had assumed, since the installer/uninstaller is a `.bat` file, that we only cared about Windows. I will research and get back to you on that.

**Comment by celluj34** [comment]
Fixed! I referenced an article here: https://medium.com/@frankkerrigan/creating-a-service-for-both-linux-systemd-and-windows-service-fe4ddfa68597

**Comment by darcymiranda** [comment]
Sweet. I only cared about the windows service because I use windows, but the console project was an option for non-windows users to run the server.

Can you also update the readme with instructions to `dotnet run` against this project instead of the now removed Console?

I suppose now we can rename the project to just `PFire.Service` now since it's cross platform. Or is there's a better name to signify that this is the "root" project? Makes me think we should rename it to Console now heh.

**Comment by celluj34** [comment]
Yeah I can rename it to whatever you'd like! In my professional projects I use `<Solution>.Console` only because I haven't found a better alternative.

**Comment by darcymiranda** [comment]
Thanks for the effort on this @celluj34! This inadvertently also sets some ground work for dotnet's DI containers which is fantastic. I'm going to merge this into another branch to make sure both aspects work. I'll probably rename WindowsService to just Console too for familiarity purposes.

**Comment by celluj34** [comment]
Yeah I was hoping you'd catch that! This definitely gives us the ability to start using DI and greatly enhances the ability for unit tests, refactoring, all sort of fun things :)

**Pull request merged**
